## Simule el primer sistema cuántico descrito en la sección 4.1.
1. El sistema debe calcular la probabilidad de encontrarlo en una posición en particular.

In [6]:
import numpy as np

def norm(a):
    return np.linalg.norm(a)

def prob_pos(ket, pos):
    num = norm(ket[pos]) ** 2
    den = norm(ket) ** 2
    return num / den


k = np.array([[-2+3j], [1-2.5j], [1+1j], [0+3j]])
prob = prob_pos(k, 2)
print("La probabilidad es:", prob*100, "%")




La probabilidad es: 6.4 %


2. El sistema si se le da otro vector Ket debe buscar la probabilidad de transitar del primer vector al segundo.

In [7]:
import numpy as np

def trans_prob(k1, k2):
    prod = np.vdot(k2, k1)
    return np.abs(prod) ** 2


k1 = np.array([[2-1j], [0+3j]])
k2 = np.array([[1+1j], [2-1.2j]])
prob = trans_prob(k1, k2)
print(f"La prob de transitar de {k1} a {k2} es:", prob)



La prob de transitar de [[2.-1.j]
 [0.+3.j]] a [[1.+1.j ]
 [2.-1.2j]] es: 15.759999999999998


## Complete los retos de programación del capítulo 4.
1. Amplitud de transición. El sistema puede recibir dos vectores y calcular la probabilidad de transitar de el uno al otro después de hacer la observación

In [1]:
import numpy as np

def amp_trans(psi, phi):
    prod = np.vdot(phi, psi)
    prob = np.abs(prod) ** 2
    return prob

psi = np.array([1, 0, 0], dtype=complex)
phi = np.array([0, 1, 0], dtype=complex)


print("Prob transición:", amp_trans(psi, phi))

Prob transición: 0.0


2. Ahora con una matriz que describa un observable y un vector ket, el sistema revisa que la matriz sea hermitiana, y si lo es, calcula la media y la varianza del observable en el estado dado.

In [2]:
def es_herm(O):
    return np.allclose(O, O.conj().T)

def med_var(ket, O):
    if not es_herm(O):
        raise ValueError("No es hermitiana")
    
    med = np.vdot(ket, np.dot(O, ket))
    O2 = np.dot(O, O)
    med_O2 = np.vdot(ket, np.dot(O2, ket))
    var = med_O2 - np.abs(med) ** 2
    
    return med, var

O = np.array([[1, 0, 0], [0, 2, 0], [0, 0, 3]], dtype=complex)
ket = np.array([1/np.sqrt(2), 1/np.sqrt(2), 0], dtype=complex)


med, var = med_var(ket, O)
print("Media:", med)
print("Varianza:", var)


Media: (1.4999999999999996+0j)
Varianza: (0.2500000000000009+0j)


3. El sistema calcula los valores propios del observable y la probabilidad de que el sistema transite a alguno de los vectores propios después de la observación.

In [4]:
def prob_vp(ket, O):

    valores_propios, vectores_propios = np.linalg.eigh(O)
    

    probabilidades = []
    for vector_propio in vectores_propios.T:
        probabilidad = np.abs(np.vdot(vector_propio, ket)) ** 2
        probabilidades.append(probabilidad)
    
    return valores_propios, probabilidades


vals, probs = prob_vp(ket, O)
print("Vals propios:", vals)
print("Probs transición:", probs)


Vals propios: [1. 2. 3.]
Probs transición: [0.4999999999999999, 0.4999999999999999, 0.0]


4. Se considera la dinámica del sistema. Ahora con una serie de matrices Un el sistema calcula el estado final a partir de un estado inicial.

In [5]:
def evo_dyn(ket0, Us):
    ket_f = ket0
    for U in Us:
        ket_f = np.dot(U, ket_f)
    return ket_f

U1 = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 1]], dtype=complex)
U2 = np.array([[1, 0, 0], [0, 0, 1], [0, 1, 0]], dtype=complex)
Us = [U1, U2]

estado_f = evo_dyn(psi, Us)
print("Estado final:", estado_f)

Estado final: [0.+0.j 0.+0.j 1.+0.j]


Exercise 4.3.1 Find all the possible states the system described in Exercise 4.2.2 can transition into after a measurement has been carried out.

In [12]:
import numpy as np

S = np.array([[0, 1], [1, 0]], dtype=complex)

vals, vecs = np.linalg.eig(S)

print("\nVectores propios:")
print(vecs)

print("Valores propios:")
print(vals)


print("El observable siempre resultará en spin down.")



Vectores propios:
[[ 0.70710678-0.j  0.70710678+0.j]
 [ 0.70710678+0.j -0.70710678-0.j]]
Valores propios:
[ 1.+0.j -1.+0.j]
El observable siempre resultará en spin down.


4.4.1 Verifique que:
$$ 
    \begin{bmatrix} 0 && 1 \\
                   1 && 0 \\
    \end{bmatrix}
    \begin{bmatrix}  √2/2 && √2/2 \\
                   √2/2 && -√2/2 \\
    \end{bmatrix}$$
son matrices unitarias. Multiplíque y verifica que su producto también sea unitario.

In [8]:
import numpy as np

def unitaria(m):

    if m.shape[0] != m.shape[1]:
        return False

    ident = np.eye(m.shape[0])
    return np.allclose(np.dot(m, m.conj().T), ident)

def ver_matrices(matrices):
    for i, m in enumerate(matrices):
        if unitaria(m):
            print(f"La matriz {i+1} es unitaria:\n", m)
        else:
            print(f"La matriz {i+1} NO es unitaria.")


m1 = np.array([[0, 1], [1, 0]])
m2 = np.array([[np.sqrt(2)/2, np.sqrt(2)/2], [np.sqrt(2)/2, -np.sqrt(2)/2]])
prod = np.dot(m1, m2)


ver_matrices([m1, m2, prod])

La matriz 1 es unitaria:
 [[0 1]
 [1 0]]
La matriz 2 es unitaria:
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
La matriz 3 es unitaria:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


4.4.2 Determinar el estado del sistema después de tres pasos de tiempo. ¿Cuál es la probabilidad de que la bola cuántica se encuentre en el punto 3?

In [9]:
import numpy as np

m = np.array([[0, 1/np.sqrt(2), 1/np.sqrt(2), 0], 
              [1j/np.sqrt(2), 0, 0, 1/np.sqrt(2)], 
              [1/np.sqrt(2), 0, 0, 1j/np.sqrt(2)], 
              [0, 1/np.sqrt(2), -1/np.sqrt(2), 0]])

v = np.array([[1], [0], [0], [0]])
c1 = np.dot(m, v)
c2 = np.dot(m, c1)
c3 = np.dot(m, c2)

print("1 click: ", c1)
print("2 clicks: ", c2)
print("3 clicks: ", c3)

n = np.linalg.norm(c3)
p = (c3[2] * np.conj(c3[2])) / (n**2)
print("Probabilidad:", p)


1 click:  [[0.        +0.j        ]
 [0.        +0.70710678j]
 [0.70710678+0.j        ]
 [0.        +0.j        ]]
2 clicks:  [[ 0.5+0.5j]
 [ 0. +0.j ]
 [ 0. +0.j ]
 [-0.5+0.5j]]
3 clicks:  [[ 0.        +0.j        ]
 [-0.70710678+0.70710678j]
 [ 0.        +0.j        ]
 [ 0.        +0.j        ]]
Probabilidad: [0.+0.j]
